//Next JS imports
import Head from 'next/head';

//React import
import { useState, useEffect } from 'react';

//Near imports
import {
    signIn,
    signOut,
    wallet,
    viewFunction,
    callFunction,
} from '../near/cryptonized';

export default function NFT() {
    const [user, setUser] = useState(null);
    // const [metadata, setMetadata] = useState(null);
    const [nft, setNft] = useState(null);

    useEffect(() => {
        if (wallet.getAccountId()) {
            setUser(wallet.getAccountId());
            viewFunction('nft_tokens_for_owner', { account_id: user }).then(
                (result) => {
                    setNft(result);
                }
            );
            createNFT();
            console.log('user', user);
        }
    }, [user]);

    const createNFT = async () => {
        await callFunction('nft_mint', {
                "token_id": "2",
                "metadata": {
                  "title": "Cryptonized",
                  "description": "My 1st NFT",
                  "media": "https://media.licdn.com/dms/image/C560BAQGnbrbibTKR6Q/company-logo_200_200/0/1672737295471?e=1680739200&v=beta&t=dhlWalKcErYK8iwwIWGmIr4C1U2SIDT43OCGDMzIn7w"
                },
                "receiver_id": "fred0.testnet"
              }
        );
    };

    return (
        <div>
            <Head>
                <title>Cryptonized</title>
                <meta
                    name='description'
                    content='Generated by create next app'
                />
                <link rel='icon' href='/favicon.ico' />
            </Head>

            <div className='m-6'>
                {!user ? (
                    <>
                        <h4>
                            Welcome to Cryptonized please connect your near
                            wallet
                        </h4>
                        <button
                            className='bg-blue-400 hover:bg-blue-500 text-white font-bold py-2 px-4 rounded'
                            onClick={() => {
                                signIn();
                            }}>
                            Sign In
                        </button>
                    </>
                ) : (
                    <>
                        <div>
                            <div>
                                <h1>Create an NFT</h1>
                            </div>
                            {nft && (
                                <div>
                                    <h1 className='text-2xl'>Your NFTs</h1>
                                    <div className='flex flex-wrap'>
                                        {nft.map((token) => (
                                            <div
                                                key={token.token_id}
                                                className='w-1/4 p-2'>
                                                <img
                                                    src={token.metadata.media}
                                                    alt={token.metadata.title}
                                                />
                                                <p>{token.metadata.title}</p>

                                                <p>
                                                    {token.metadata.description}
                                                </p>
                                            </div>
                                        ))}
                                    </div>
                                </div>
                            )}
                        </div>
                        <button
                            className='bg-blue-400 hover:bg-blue-500 text-white font-bold py-2 px-4 rounded my-1'
                            onClick={() => {
                                signOut();
                                setUser(null);
                            }}>
                            Sign out
                        </button>
                    </>
                )}
            </div>
        </div>
    );
}
